version: '3.7'

services:
  chat-server:
    build:
      context: ../
      dockerfile: build/package/Dockerfile
    image: local-chat-server
    environment:
      TZ: "Europe/Moscow"
      PGHOST: "postgres"
      PGPORT: 5432
      PGDATABASE: "dev"
      PGUSER: "kris"
      PGPASSWORD: "changeme"
      PGSSLMODE: "disable"
    ports:
      - "9000:9000"

  postgres:
    image: postgres:12.3
    init: true
    environment:
      POSTGRES_USER: "kris"
      POSTGRES_PASSWORD: "changeme"
      PGDATA: "/var/lib/postgresql/data/sampleDir"
      POSTGRES_DB: "dev"
    ports:
      - "15432:5432"
    volumes:
      - ${PWD}/scripts/postgres:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    init: true
    environment:
      PGADMIN_DEFAULT_EMAIL: "1"
      PGADMIN_DEFAULT_PASSWORD: "1"
    ports:
      - "16543:80"
    depends_on:
      - postgres
