notifications:
  email: false

language: go

go:
  - 1.14.x

services:
  - docker

before_install:
  - docker-compose -f ./deployments/docker-compose.yml up -d postgres
  # debugging calls
  - docker-compose -f ./deployments/docker-compose.yml ps
  - docker-compose -f ./deployments/docker-compose.yml logs
#  - docker exec -it $(docker ps -q) psql -U kris -d dev -c 'select * from public.users;'
  - netstat -a

script:
  # build test for supported platforms
  # - GOOS=linux go build
  # - GOOS=windows go build

  # run tests on a standard platform
  - go test -v ./... -coverprofile=coverage.txt -covermode=atomic
  - go test -v ./... -race

after_success:
  # Upload coverage results to codecov.io
  - bash <(curl -s https://codecov.io/bash)