language: go

go:
  - 1.14.x

sudo: true
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

env:
  global:
    - PGPORT=5432

before_install:
  - sudo -u postgres psql -c "CREATE DATABASE dev"
  - sudo -u postgres psql -c "CREATE USER kris WITH PASSWORD `changeme`"
  - sudo -u postgres psql -d dev -f -a ./deployments/schema.sql

script:
  # build test for supported platforms
  - GOOS=linux go build
  - GOOS=windows go build

  # run tests on a standard platform
  - go test -v ./... -coverprofile=coverage.txt -covermode=atomic
  - go test -v ./... -race

after_success:
  # Upload coverage results to codecov.io
  - bash <(curl -s https://codecov.io/bash)